// Generated by the ZIP export — data only, never source code.
export const ENABLED_FEATURES = [
  "agent",
  "email-tracking"
];

export const isFeatureEnabled = (id) => ENABLED_FEATURES.includes(id);
