// Generated by the ZIP export — data only, never source code.
export const ENABLED_SETTINGS_SECTIONS = [
  "users",
  "system-features",
  "capabilities",
  "custom-fields",
  "integrations",
  "supabase",
  "project-tabs",
  "popups",
  "notifications",
  "branding"
];

export const isSectionEnabled = (id) => ENABLED_SETTINGS_SECTIONS.includes(id);
