// ─────────────────────────────────────────────────────────────────────────────
// EXPORT CORE — pure functions over a virtual file map { path: contents }.
//
// No `fs`, no `window`. Both consumers use this same code, so the ZIP produced
// by the in-app button and by `npm run export` is identical:
//   • tools/export-zip.js   — Node adapter, reads from disk
//   • src/lib/browserExport.js — browser adapter, reads from import.meta.glob
// ─────────────────────────────────────────────────────────────────────────────

export const ROOT_FILE_ALLOWLIST = [
  'index.html', 'package.json', 'jsconfig.json', 'components.json',
  'postcss.config.js', 'tailwind.config.js', 'vite.config.js', 'vitest.config.js',
  'eslint.config.js', 'vercel.json', 'netlify.toml',
  'README.md', 'DESIGN_SYSTEM.md',
];

// Dotfiles are generated rather than copied: Vite denies reading `.env*` and
// skips dotfiles in import.meta.glob, so neither adapter can reliably read them.
// This constant is the single source of truth for both.
export const STATIC_FILES = {
  '.env.example': [
    '# Deployment owner — the account that is treated as the first admin.',
    "# Never commit a real address here; set it in .env.local or your host's env vars.",
    // Blank on purpose: an exported bundle must not arrive pre-filled with a
    // sample account or with someone else's product name.
    'VITE_OWNER_EMAIL=',
    'VITE_OWNER_NAME=',
    '',
    '# Branding. Left empty on purpose — set it here or in הגדרות → מיתוג.',
    'VITE_APP_NAME=',
    'VITE_APP_LOGO_URL=',
    '',
  ].join('\n'),
  '.gitignore': ['node_modules', 'dist', '.env', '.env.local', '*.zip', '.DS_Store', ''].join('\n'),
};

export const ROOT_DIR_ALLOWLIST = ['public/', 'docs/'];
export const DEV_TOOL_DIRS = ['tools/'];

export const TOOLCHAIN_DEPS = new Set([
  'vite', '@vitejs/plugin-react', 'tailwindcss', 'tailwindcss-animate',
  'postcss', 'postcss-rtlcss', 'autoprefixer', 'typescript',
  '@types/node', '@types/react', '@types/react-dom',
  'eslint', '@eslint/js', 'eslint-plugin-react', 'eslint-plugin-react-hooks',
  'eslint-plugin-react-refresh', 'eslint-plugin-unused-imports', 'globals',
]);

export const DEV_TOOL_DEPS = new Set([
  'jszip', 'vitest', '@vitest/coverage-v8', 'jsdom',
  '@testing-library/react', '@testing-library/jest-dom', '@testing-library/user-event',
]);

export const NEVER_EXPORT_DEPS = new Set([
  'archiver', 'baseline-browser-mapping',
]);

export const SETTINGS_PANEL_FILES = {
  'users': 'src/components/settings/UserManagementPanel.jsx',
  'system-features': 'src/components/settings/GlobalSystemFeaturesPanel.jsx',
  'capabilities': 'src/components/settings/CapabilitiesPanel.jsx',
  'custom-fields': 'src/components/settings/CustomFieldsPanel.jsx',
  'integrations': 'src/components/settings/IntegrationsPanel.jsx',
  'supabase': 'src/components/settings/SupabasePanel.jsx',
  'project-tabs': 'src/components/settings/GlobalTabVisibilityPanel.jsx',
  'popups': 'src/components/settings/PopupManagementPanel.jsx',
  'notifications': 'src/components/settings/NotificationsCenterPanel.jsx',
  'branding': 'src/components/settings/BrandingPanel.jsx',
};

export const CORE_PAGES = ['Profile', 'Notifications', 'FirstTimeSetup'];

// Optional features. Their files are reachable only through a build-time glob,
// so they must be seeded explicitly when the feature is switched on.
export const OPTIONAL_FEATURES = {
  agent: {
    label: 'עוזר חכם (Agent)',
    files: [
      'src/components/shared/SystemAssistantSheet.jsx',
      'src/components/shared/AgentTraceCard.jsx',
      'src/components/shared/AssistantEmptyState.jsx',
      'src/components/project/ProjectAIChat.jsx',
      'src/components/development/ReportsAIChat.jsx',
    ],
  },
  'email-tracking': {
    label: 'מעקב מיילים',
    files: ['src/components/profile/OutboxTab.jsx'],
  },
};

export const featuresFile = (features) =>
  '// Generated by the ZIP export — data only, never source code.\n' +
  `export const ENABLED_FEATURES = ${JSON.stringify(features, null, 2)};\n\n` +
  'export const isFeatureEnabled = (id) => ENABLED_FEATURES.includes(id);\n';

export const appIdentityFile = (identity) =>
  '// Generated by the ZIP export — data only, never source code.\n' +
  `export const APP_IDENTITY = ${JSON.stringify(identity, null, 2)};\n\n` +
  'export const isBlankTemplate = () => !APP_IDENTITY.name;\n';

export const BLANK_IDENTITY = {
  name: '',
  subtitle: '',
  logo: '',
  company: { tagline: '', legalId: '', address: '', paymentTerms: '', bank: '' },
};

/** Merge a caller-supplied identity over the blank template. */
export const buildIdentity = (identity = {}) => ({
  ...BLANK_IDENTITY,
  ...identity,
  company: { ...BLANK_IDENTITY.company, ...(identity.company || {}) },
});

const RESOLVE_EXTS = ['', '.jsx', '.js', '.ts', '.tsx', '.json', '.css'];
const INDEX_FILES = ['/index.jsx', '/index.js', '/index.ts', '/index.tsx'];

/** Parse src/lib/modules.js into { moduleId: [pageName, ...] }. */
export function parseModuleManifest(source) {
  const pages = {};
  const blocks = source.split(/^\s{2}(\w+):\s*\{$/m);
  for (let i = 1; i < blocks.length; i += 2) {
    const id = blocks[i];
    const found = [...(blocks[i + 1] || '').matchAll(/page:\s*'([^']+)'/g)].map((m) => m[1]);
    if (found.length) pages[id] = found;
  }
  return pages;
}

export function extractSpecifiers(code) {
  const out = [];
  const patterns = [
    /\bimport\s+[^'"();]*?\bfrom\s*['"]([^'"]+)['"]/g,
    /\bimport\s*['"]([^'"]+)['"]/g,
    /\bexport\s+[^'"();]*?\bfrom\s*['"]([^'"]+)['"]/g,
    /\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
    /\brequire\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
    /@import\s+['"]([^'"]+)['"]/g,
  ];
  for (const re of patterns) {
    let m;
    while ((m = re.exec(code)) !== null) out.push(m[1]);
  }
  return out;
}

const dirname = (p) => p.slice(0, p.lastIndexOf('/') + 1) || './';

function normalize(p) {
  const parts = [];
  for (const seg of p.split('/')) {
    if (seg === '.' || seg === '') continue;
    if (seg === '..') parts.pop();
    else parts.push(seg);
  }
  return parts.join('/');
}

function tryPaths(base, has) {
  for (const ext of RESOLVE_EXTS) if (has(base + ext)) return base + ext;
  for (const idx of INDEX_FILES) if (has(base + idx)) return base + idx;
  return null;
}

export function resolveSpecifier(rawSpec, fromFile, has) {
  // Vite query suffixes (?raw, ?url, ?worker…) are not part of the path.
  const spec = rawSpec.split('?')[0];
  if (!spec) return null;
  if (spec.startsWith('@/')) return tryPaths(normalize('src/' + spec.slice(2)), has);
  if (spec.startsWith('/')) return tryPaths(normalize(spec.slice(1)), has);
  if (spec.startsWith('.')) return tryPaths(normalize(dirname(fromFile) + spec), has);
  return null;
}

export function packageNameOf(rawSpec) {
  const spec = rawSpec.split('?')[0];
  if (!spec) return null;
  if (spec.startsWith('.') || spec.startsWith('/') || spec.startsWith('@/')) return null;
  if (spec.startsWith('node:')) return null;
  const parts = spec.split('/');
  return spec.startsWith('@') ? parts.slice(0, 2).join('/') : parts[0];
}

/**
 * Breadth-first walk of the import graph.
 * @param {(p:string)=>boolean} has   does this path exist?
 * @param {(p:string)=>string}  read  text contents of a path
 */
export function walkGraph(entries, has, read) {
  const included = new Set();
  const packages = new Set();
  const missing = [];
  const queue = [...entries];

  while (queue.length) {
    const file = queue.shift();
    if (included.has(file)) continue;
    if (!has(file)) { missing.push({ file: '(entry)', spec: file }); continue; }
    included.add(file);
    if (!/\.(jsx?|tsx?|css)$/.test(file)) continue;

    for (const spec of extractSpecifiers(read(file) || '')) {
      if (spec.includes('*')) continue; // import.meta.glob resolves against shipped files
      const pkg = packageNameOf(spec);
      if (pkg) { packages.add(pkg); continue; }
      const resolved = resolveSpecifier(spec, file, has);
      if (!resolved) { missing.push({ file, spec }); continue; }
      if (!included.has(resolved)) queue.push(resolved);
    }
  }
  return { included, packages, missing };
}

export function prunePackageJson(pkg, usedPackages, devTools) {
  const keep = (deps = {}) =>
    Object.fromEntries(
      Object.entries(deps).filter(([name]) =>
        !NEVER_EXPORT_DEPS.has(name) &&
        (usedPackages.has(name) || TOOLCHAIN_DEPS.has(name) || (devTools && DEV_TOOL_DEPS.has(name)))
      )
    );
  const out = {
    ...pkg,
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
      lint: 'eslint . --quiet',
      ...(devTools ? {
        test: 'vitest run',
        'test:watch': 'vitest',
        export: 'node tools/export-cli.js',
        verify: 'node tools/export-matrix.js',
      } : {}),
    },
    dependencies: keep(pkg.dependencies),
    devDependencies: keep(pkg.devDependencies),
  };
  const dropped = [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.devDependencies || {}),
  ].filter((n) => !out.dependencies[n] && !out.devDependencies[n]);
  return { pkg: out, dropped };
}

export function settingsSectionsFile(sections) {
  return (
    '// Generated by the ZIP export — data only, never source code.\n' +
    `export const ENABLED_SETTINGS_SECTIONS = ${JSON.stringify(sections, null, 2)};\n\n` +
    'export const isSectionEnabled = (id) => ENABLED_SETTINGS_SECTIONS.includes(id);\n'
  );
}

/**
 * Decide exactly what goes into the archive.
 * Throws with a readable report if anything would fail to build.
 *
 * @returns {{ textFiles: Map<string,string>, copyPaths: string[], meta: object }}
 */
export function planExport({ has, read, allPaths, options = {} }) {
  const manifestSrc = read('src/lib/modules.js');
  if (!manifestSrc) throw new Error('src/lib/modules.js לא נמצא — לא ניתן לייצא');
  const modulePages = parseModuleManifest(manifestSrc);
  const allModules = Object.keys(modulePages);

  // "All" means all modules present in THIS bundle, not everything the manifest
  // declares — a partial export still carries the full manifest.
  const availableModules = allModules.filter((id) =>
    (modulePages[id] || []).some((page) => has(`src/pages/${page}.jsx`))
  );
  const modules = options.modules?.length ? options.modules : availableModules;
  const sections = options.settingsSections?.length
    ? options.settingsSections
    : Object.keys(SETTINGS_PANEL_FILES);
  const devTools = options.devTools !== false;
  // Branding supplied by the export step. When present the bundle ships already
  // branded for that client — nothing to configure after deploying.
  const identity = options.identity ? buildIdentity(options.identity) : null;
  const blankTemplate = options.blankTemplate === true || (!!identity && !identity.name);
  const features = Object.keys(OPTIONAL_FEATURES).filter((id) =>
    options.features ? options.features.includes(id) : true
  );

  const unknown = modules.filter((m) => !allModules.includes(m));
  if (unknown.length) throw new Error(`מודולים לא מוכרים: ${unknown.join(', ')}`);

  const absent = modules.filter((m) => !availableModules.includes(m));
  if (absent.length) {
    throw new Error(
      `המודולים הבאים אינם קיימים בחבילה הזו ולכן לא ניתן לייצא אותם: ${absent.join(', ')}\n` +
      `זמינים כאן: ${availableModules.join(', ')}`
    );
  }
  if (modules.length === 0) throw new Error('לא נבחר אף מודול');

  const entries = new Set(['index.html', 'src/main.jsx', 'src/index.css']);
  for (const mod of modules) for (const p of modulePages[mod] || []) entries.add(`src/pages/${p}.jsx`);
  for (const p of CORE_PAGES) entries.add(`src/pages/${p}.jsx`);
  if (modules.includes('settings')) {
    for (const id of sections) {
      const f = SETTINGS_PANEL_FILES[id];
      if (f && has(f)) entries.add(f);
    }
    // The export UI is only reachable through a glob, so seed it explicitly —
    // and only when this bundle is meant to keep exporting.
    if (devTools) entries.add('src/components/settings/ExportDialog.jsx');
  }
  for (const id of features) {
    for (const f of OPTIONAL_FEATURES[id].files) if (has(f)) entries.add(f);
  }

  const { included, packages, missing } = walkGraph([...entries], has, read);

  if (missing.length) {
    const report = missing.slice(0, 40).map((m) => `  • ${m.file} → '${m.spec}'`).join('\n');
    throw new Error(`הייצוא נעצר: ${missing.length} ייבוא לא נפתר. החבילה לא הייתה נבנית.\n${report}`);
  }

  const textFiles = new Map();
  const copyPaths = [];

  const isBinary = (p) => /\.(png|jpe?g|gif|webp|ico|woff2?|ttf|otf|pdf|zip)$/i.test(p);
  const add = (p) => {
    if (!has(p)) return;
    if (isBinary(p)) copyPaths.push(p);
    else textFiles.set(p, read(p));
  };

  for (const name of ROOT_FILE_ALLOWLIST) add(name);
  for (const [name, content] of Object.entries(STATIC_FILES)) textFiles.set(name, content);
  for (const p of allPaths) {
    if (ROOT_DIR_ALLOWLIST.some((d) => p.startsWith(d))) add(p);
    if (devTools && DEV_TOOL_DIRS.some((d) => p.startsWith(d))) add(p);
  }

  for (const file of included) {
    if (!devTools && (/\.test\.(jsx?|tsx?)$/.test(file) || file.startsWith('src/test/'))) continue;
    add(file);
  }

  if (devTools) {
    // A test only ships when everything it imports is also in the bundle.
    // Otherwise a partial export carries a test for a module it does not have,
    // and `npm test` fails on a bundle that is otherwise perfectly fine.
    const included = new Set([...textFiles.keys(), ...copyPaths]);
    const resolvesInBundle = (file, content) =>
      extractSpecifiers(content).every((spec) => {
        // Node builtins resolve to nothing on disk but are always available.
        if (spec.startsWith('node:') || spec.includes('*') || packageNameOf(spec)) return true;
        const target = resolveSpecifier(spec, file, has);
        return target ? included.has(target) : false;
      });

    for (const p of allPaths) {
      if (p.startsWith('src/test/')) { add(p); continue; }
      if (!/^src\/.*\.test\.(jsx?|tsx?)$/.test(p)) continue;
      const content = read(p);
      if (content && resolvesInBundle(p, content)) add(p);
    }
  }

  // The only generated source files — all pure data, no code surgery.
  textFiles.set('src/lib/settingsSections.js', settingsSectionsFile(sections));
  textFiles.set('src/lib/features.js', featuresFile(features));

  if (identity || blankTemplate) {
    const applied = identity || BLANK_IDENTITY;
    const displayName = applied.name || 'App';
    const fullName = [applied.name, applied.subtitle].filter(Boolean).join(' — ') || 'App';

    textFiles.set('src/lib/appIdentity.js', appIdentityFile(applied));

    const manifest = JSON.parse(read('public/manifest.json') || '{}');
    // A data-URL logo is embedded straight into the manifest; the original brand
    // icons are dropped either way so no borrowed asset ever ships.
    const icons = applied.logo?.startsWith('data:')
      ? [{ src: applied.logo, sizes: '512x512', type: 'image/png', purpose: 'any maskable' }]
      : applied.logo && !applied.logo.startsWith('/icon-')
        ? [{ src: applied.logo, sizes: '512x512', type: 'image/png', purpose: 'any maskable' }]
        : [];
    textFiles.set('public/manifest.json', JSON.stringify({
      ...manifest,
      name: fullName,
      short_name: displayName,
      description: applied.subtitle || '',
      icons,
    }, null, 2) + '\n');
    // Drop the original brand assets rather than shipping someone else's logo.
    for (let i = copyPaths.length - 1; i >= 0; i--) {
      if (/^public\/icon-/.test(copyPaths[i])) copyPaths.splice(i, 1);
    }
    // Every human-visible string in the shell is emptied, so the template
    // carries no trace of the product it was exported from.
    textFiles.set('README.md', [
      `# ${displayName}`, '',
      applied.name
        ? `${[applied.name, applied.subtitle].filter(Boolean).join(' — ')}. Vite + React, עברית RTL.`
        : 'תבנית ריקה — Vite + React, עברית RTL, ללא מיתוג.', '',
      '```bash', 'npm install', 'cp .env.example .env.local', 'npm run dev', '```', '',
      'מיתוג: `הגדרות → אדמין → מיתוג`. מודולים ומסלולים: `src/lib/modules.js`.',
      'ייצוא ופריסה: `docs/DEPLOYMENT.md`.', '',
    ].join('\n'));

    const html = textFiles.get('index.html');
    if (html) {
      textFiles.set('index.html', html
        .replace(/<title>[\s\S]*?<\/title>/, `<title>${fullName}</title>`)
        .replace(/(<meta\s+(?:name|property)="(?:og:title|apple-mobile-web-app-title)"\s+content=")[^"]*"/g, `$1${fullName}"`)
        .replace(/(<meta\s+(?:name|property)="(?:description|og:description|og:site_name)"\s+content=")[^"]*"/g, `$1${applied.subtitle || ''}"`));
    }
  }

  const originalPkg = JSON.parse(read('package.json'));
  const { pkg, dropped } = prunePackageJson(originalPkg, packages, devTools);
  textFiles.set('package.json', JSON.stringify(pkg, null, 2) + '\n');

  const meta = {
    modules,
    availableModules,
    features,
    blankTemplate,
    identity: identity ? { name: identity.name, subtitle: identity.subtitle, hasLogo: !!identity.logo } : null,
    settingsSections: sections,
    devTools,
    files: included.size,
    droppedDependencies: dropped,
    exportedAt: new Date().toISOString(),
  };
  textFiles.set('selected_modules.json', JSON.stringify(meta, null, 2));

  return { textFiles, copyPaths, meta };
}
